Updated driver device files to select args to pass based on scenario
Xilinx/ACCL pull request #175
Opened 2023-11-23 10:42 UTC by mar-ven

Modified coyotedevice.cpp and fpgadevice.cpp in driver/xrt/src to specifiy which args to pass based on scenario. 
Added the header file commands.hpp in driver/xrt/include/accl to specify the arg id for fpgadevice.cpp args. Previous implementation automatically increased arg id by 1, but now some args are skipped based on scenario, so arg value must be provided explicitly.

2023-11-24 17:50 UTC, quetric requested changes

2023-11-24 17:50 UTC, quetric commented on driver/xrt/include/accl/commands.hpp
These should go into constants.hpp and the format should be <name>_ARG_ID

2023-11-28 10:50 UTC, mar-ven commented
I moved the definitions into constants.hpp and used the namespace XRT_ARG_ID to embed them, in order to be consistent with the content of that header file

2023-12-07 11:16 UTC, quetric approved these changes

2023-12-07 11:38 UTC, merged