Small fixes in ZMQ client and firmware
Xilinx/ACCL pull request #94
Opened 2022-10-05 08:04 UTC by Mellich

Fix a bug in the subscription of the ZMQ client. Allow stream_put with same source and destination rank.

2022-10-17 14:20 UTC, quetric commented
I don't want to carry around the dummy buffers if it can be avoided. I'd rather add new signatures to the copy/put/etc for streaming functionality. Even better if we get to hide the stream flags in the process.

@TristanLaan any feedback on the feasibility of implementing stream-specific signatures for these ops?

@Marius can we consolidate all issues and PRs touched by this API decision into a single PR?

2022-10-17 14:49 UTC, TristanLaan commented
> @TristanLaan any feedback on the feasibility of implementing stream-specific signatures for these ops?

Should be very simple, I don't see anything preventing us from implementing this.

2022-10-18 16:58 UTC, Mellich commented
Updated, but there is still the issue with #99. For the special case source rank = destination rank the stream ID seems to get ignored. It seems this would require some changes in the CCLO. How do we handle this?

2022-10-19 07:02 UTC, quetric requested changes

2022-10-19 07:02 UTC, quetric commented on test/host/hls/test.cpp
> +#include "dummybuffer.hpp"
is this still required here?

2022-10-19 10:33 UTC, Mellich commented on test/host/hls/test.cpp
> +#include "dummybuffer.hpp"
No, deleted it.

2022-10-21 13:24 UTC, TristanLaan approved these changes

2022-10-21 13:25 UTC, merged